resilience4j.circuitbreaker:
  instances:
    buscarClientePorIdCB:
      minimumNumberOfCalls: 4
      slidingWindowSize: 8
    buscarContaPorIdCB:
      minimumNumberOfCalls: 4
      slidingWindowSize: 8
    atualizarSaldoCB:
      minimumNumberOfCalls: 4
      slidingWindowSize: 8
    notificarBACENCB:
      minimumNumberOfCalls: 4
      slidingWindowSize: 8